/**
 * CRM System - Lead Pipeline & Contact Management
 */
const CONFIG = { SHEET_NAMES: { USERS: 'Users', CONTACTS: 'Contacts', COMPANIES: 'Companies', DEALS: 'Deals', ACTIVITIES: 'Activities', AUDIT_LOG: 'AuditLog' }, DEAL_STAGES: ['Lead', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'], STAGE_COLORS: { Lead: '#9CA3AF', Qualified: '#3B82F6', Proposal: '#8B5CF6', Negotiation: '#F59E0B', Won: '#10B981', Lost: '#EF4444' } };
function getSheet(name) { const ss = SpreadsheetApp.getActiveSpreadsheet(); let sheet = ss.getSheetByName(name); if (!sheet) { sheet = ss.insertSheet(name); setupHeaders(sheet, name); } return sheet; }
function setupHeaders(sheet, name) { const h = { Users: ['Email', 'Name', 'Role', 'Department', 'Active'], Contacts: ['ContactID', 'FirstName', 'LastName', 'Email', 'Phone', 'CompanyID', 'Designation', 'Owner', 'CreatedAt'], Companies: ['CompanyID', 'Name', 'Industry', 'Website', 'Size', 'Location', 'Owner', 'CreatedAt'], Deals: ['DealID', 'Title', 'Value', 'Stage', 'ContactID', 'CompanyID', 'Probability', 'ExpectedClose', 'Owner', 'Notes', 'CreatedAt', 'UpdatedAt'], Activities: ['ActivityID', 'Type', 'Subject', 'DealID', 'ContactID', 'Date', 'Duration', 'Notes', 'CreatedBy', 'CreatedAt'], AuditLog: ['Timestamp', 'User', 'Action', 'RecordID', 'OldValue', 'NewValue'] }; if (h[name]) { sheet.getRange(1, 1, 1, h[name].length).setValues([h[name]]); sheet.getRange(1, 1, 1, h[name].length).setFontWeight('bold'); } }
function generateId(prefix) { return prefix + '-' + Utilities.getUuid().substring(0, 8).toUpperCase(); }
function getCurrentUser() { const email = Session.getActiveUser().getEmail(); const sheet = getSheet(CONFIG.SHEET_NAMES.USERS); const data = sheet.getDataRange().getValues(); for (let i = 1; i < data.length; i++) { if (data[i][0].toLowerCase() === email.toLowerCase()) return { email: data[i][0], name: data[i][1], role: data[i][2] }; } return { email, name: 'Unknown', role: 'Employee' }; }
function logAction(action, recordId, oldValue, newValue) { const sheet = getSheet(CONFIG.SHEET_NAMES.AUDIT_LOG); sheet.appendRow([new Date(), Session.getActiveUser().getEmail(), action, recordId, oldValue, newValue]); }
function addContact(firstName, lastName, email, phone, companyID, designation) { const user = getCurrentUser(); const contactID = generateId('CNT'); const sheet = getSheet(CONFIG.SHEET_NAMES.CONTACTS); sheet.appendRow([contactID, firstName, lastName, email, phone, companyID || '', designation, user.email, new Date()]); logAction('ADD_CONTACT', contactID, '', firstName + ' ' + lastName); return { success: true, contactID }; }
function addCompany(name, industry, website, size, location) { const user = getCurrentUser(); const companyID = generateId('CMP'); const sheet = getSheet(CONFIG.SHEET_NAMES.COMPANIES); sheet.appendRow([companyID, name, industry, website, size, location, user.email, new Date()]); logAction('ADD_COMPANY', companyID, '', name); return { success: true, companyID }; }
function addDeal(title, value, stage, contactID, companyID, expectedClose, notes) { const user = getCurrentUser(); const dealID = generateId('DL'); const probability = { Lead: 10, Qualified: 25, Proposal: 50, Negotiation: 75, Won: 100, Lost: 0 }[stage] || 10; const sheet = getSheet(CONFIG.SHEET_NAMES.DEALS); sheet.appendRow([dealID, title, value, stage, contactID || '', companyID || '', probability, expectedClose ? new Date(expectedClose) : '', user.email, notes || '', new Date(), new Date()]); logAction('ADD_DEAL', dealID, '', title); return { success: true, dealID }; }
function updateDealStage(dealID, newStage) { const sheet = getSheet(CONFIG.SHEET_NAMES.DEALS); const data = sheet.getDataRange().getValues(); for (let i = 1; i < data.length; i++) { if (data[i][0] === dealID) { const oldStage = data[i][3]; const newProb = { Lead: 10, Qualified: 25, Proposal: 50, Negotiation: 75, Won: 100, Lost: 0 }[newStage] || 10; sheet.getRange(i + 1, 4, 1, 1).setValue(newStage); sheet.getRange(i + 1, 7, 1, 1).setValue(newProb); sheet.getRange(i + 1, 12, 1, 1).setValue(new Date()); logAction('UPDATE_DEAL_STAGE', dealID, oldStage, newStage); return { success: true }; } } throw new Error('Deal not found'); }
function addActivity(type, subject, dealID, contactID, date, duration, notes) { const user = getCurrentUser(); const activityID = generateId('ACT'); const sheet = getSheet(CONFIG.SHEET_NAMES.ACTIVITIES); sheet.appendRow([activityID, type, subject, dealID || '', contactID || '', new Date(date), duration || '', notes || '', user.email, new Date()]); logAction('ADD_ACTIVITY', activityID, '', type + ': ' + subject); return { success: true, activityID }; }
function getAllContacts() { const sheet = getSheet(CONFIG.SHEET_NAMES.CONTACTS); const data = sheet.getDataRange().getValues(); const contacts = []; for (let i = 1; i < data.length; i++) { contacts.push({ contactID: data[i][0], firstName: data[i][1], lastName: data[i][2], email: data[i][3], phone: data[i][4], companyID: data[i][5], designation: data[i][6], owner: data[i][7], createdAt: data[i][8] }); } return contacts; }
function getAllCompanies() { const sheet = getSheet(CONFIG.SHEET_NAMES.COMPANIES); const data = sheet.getDataRange().getValues(); const companies = []; for (let i = 1; i < data.length; i++) { companies.push({ companyID: data[i][0], name: data[i][1], industry: data[i][2], website: data[i][3], size: data[i][4], location: data[i][5], owner: data[i][6] }); } return companies; }
function getAllDeals() { const sheet = getSheet(CONFIG.SHEET_NAMES.DEALS); const data = sheet.getDataRange().getValues(); const deals = []; for (let i = 1; i < data.length; i++) { deals.push({ dealID: data[i][0], title: data[i][1], value: data[i][2], stage: data[i][3], contactID: data[i][4], companyID: data[i][5], probability: data[i][6], expectedClose: data[i][7], owner: data[i][8], notes: data[i][9], createdAt: data[i][10], updatedAt: data[i][11] }); } return deals; }
function getDashboardData() { const deals = getAllDeals(); const contacts = getAllContacts(); const companies = getAllCompanies(); const totalValue = deals.reduce((sum, d) => sum + (d.stage !== 'Lost' ? d.value : 0), 0); const pipeline = {}; CONFIG.DEAL_STAGES.forEach(s => { pipeline[s] = { count: 0, value: 0 }; deals.forEach(d => { if (d.stage === s) { pipeline[s].count++; pipeline[s].value += d.value; } }); }); return { totalValue, dealCount: deals.length, contactCount: contacts.length, companyCount: companies.length, pipeline }; }
function doGet(e) { return HtmlService.createTemplateFromFile('Index').evaluate().setTitle('CRM System').addMetaTag('viewport', 'width=device-width, initial-scale=1').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL); }
function include(filename) { return HtmlService.createHtmlOutputFromFile(filename).getContent(); }
